#! /usr/bin/env bash

if [ $# != 1 ]; then
    echo "usage: `basename $0` <filename>"
    exit 1
fi

`dirname $0`/diff-remove-timestamps \
    | `dirname $0`/diff-remove-uids \
    | `dirname $0`/diff-sort \
    | eval $addl

